### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub:   Line starting 'Roxyg ...' is malformed!

### ISSUE THREAD

**Issue by jlubega** [statnmap/HatchedPolygons#4]
Hi,

I have attempted to install your package with devtools::install_github("statnmap/HatchedPolygons") but I get the above error. Could you please advise on what I should do? I attempted to uninstall and reinstall devtools with all its dependencies but that never resolved the problem.

Thanks,
Jude.

**Comment by statnmap** [comment]
I am not sure what can cause this. 
Can you try to install without updating dependencies ?
`remotes::install_github("statnmap/HatchedPolygons", upgrade = "never")` 

Can you share the complete console output ?

**Comment by jlubega** [comment]
`remotes::install_github("statnmap/HatchedPolygons", upgrade = "never")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyg ...' is malformed!`

Same output as before

**Comment by statnmap** [comment]
I cannot reproduce this. Are you behind a Proxy ?
Are you allowed to download packages from GitHub ?  
Can you try with another one like: `devtools::install_github("ThinkR-open/attachment")`

**Comment by jlubega** [comment]
I was able to install the attachment package.

**Comment by johrstrom** [comment]
I'm not running into this, but have in the past before. When it happened to me, I need to change my `LANG` environment variable because it defaulted to C (or ANSI_C) - in any case it was getting tripped up on non utf-8 characters (probably an author or similar with latin characters).

Of course, this was in a Dockerfile so I just added this below to the Dockerfile.

```
ENV LANG=C.UTF-8
```
