### ISSUE TITLE
Latest version on CRAN not compatible with R 4.1.0

### ISSUE THREAD

**Issue by morrismc99** [statnmap/HatchedPolygons#5]
I just wanted to bring to your attention that the latest version of HatchedPolygons on CRAN does not appear to be compatible with R 4.1.0, which I just upgraded to. I have been able to successfully install it directly through devtools:github... install. Just thought you'd want to know!

**Comment by statnmap** [comment]
Hi,
This package is not available on CRAN. I did not submit it.  
But I understand that the message of `install.packages()` saying that "it is not available for this version" is misleading, because it does not tell you that this package never appeared on CRAN before. 
Thank you for the information anyway. This could have been a problem I did not see.
