### ISSUE TITLE
CRAN plan

### ISSUE THREAD

**Issue by kongdd** [statnmap/HatchedPolygons#8]
Any plan of submiting this package to CRAN?
This is a very useful package. 
I need to import it to my package `gg.layers`. If this package is not registered on CRAN, my package also can not be registered.

**Comment by statnmap** [comment]
Dear @kongdd ,

I do not plan to submit the present package on CRAN because I do not plan to maintain this code.  
Indeed, this is an export from {sp} that is not optimised. This would require too much rework to make it proper for {sf} objects.  
By the way, as for {ggplot2} integration as you did, I think it already exists in {ggpattern} and is even better than my code: https://coolbutuseless.github.io/package/ggpattern/index.html, which is on CRAN.  

So, if you still want to keep my code in your package as you already did, the way you cited it inside the code suits me.

Regards,
Sébastien

**Comment by kongdd** [comment]
`HatchedPolygons` works better for me (<https://github.com/coolbutuseless/ggpattern/issues/70>). 
Thanks for your awesome work.

**Comment by kongdd** [comment]
sp has been immigrated into sf. It becomes more simple. Welcome to test
<https://github.com/rpkgs/gg.layers/blob/master/R/st_hatched_polygon.R>
